#!/usr/bin/env python3
"""
Footer Generator
================

Generates a slim shared footer HTML file used by all Quarto sites.
Copyright/license + CTA links only. Social links and paper listings
do not live in the core conversion pages.

Usage:
    from dih_models.footer_generator import generate_footer_html
    generate_footer_html(project_root)

Output:
    assets/html/generated-footer.html
"""

import logging
import sys
from pathlib import Path

from dih_models.yaml_utils import load_quarto_config

logger = logging.getLogger("dih.footer")


def _build_cta_html(project_root: Path) -> str:
    """Build a conversion-focused CTA row: direct Amazon buy + vote link."""
    manual_config = load_quarto_config(project_root / "_quarto-manual.yml")
    buy_links = manual_config.get("links", {}).get("buy", [])

    # First buy link is the primary (Amazon Paperback)
    amazon_url = buy_links[0]["url"] if buy_links else "https://www.amazon.com/dp/B0GPLXFMMT"

    return f"""  <p class="book-footer-cta">
    <a href="{amazon_url}" class="book-footer-link book-footer-link-bold">Buy on Amazon</a> &nbsp;|&nbsp;
    <a href="https://manual.WarOnDisease.org/knowledge/links.html" class="book-footer-link">Listen</a> &nbsp;|&nbsp;
    <a href="https://WarOnDisease.org" class="book-footer-link">Vote</a> &nbsp;|&nbsp;
    <a href="https://github.com/sponsors/wishonia" class="book-footer-link">&#10084; Support this work</a>
  </p>"""


def generate_footer_html(project_root: Path) -> Path:
    """
    Generate assets/html/generated-footer.html shared by all sites.

    Slim footer: copyright/license + direct Amazon buy link + CTA.
    Keep the footer focused on direct conversion CTAs.

    Returns:
        Path to the generated file
    """
    cta_html = _build_cta_html(project_root)

    html_content = f"""<!-- AUTO-GENERATED: Shared Footer Content -->
<!-- Generated by dih_models/footer_generator.py -->
<!-- Do not edit manually - regenerate with generate-everything script -->
<div class="book-footer">
  <p class="book-footer-line">
    &copy; 2026 <a href="https://acceleratedmedicine.org" class="book-footer-link">The Institute for Accelerated Medicine</a> |
    <a href="https://mikesinn.com" class="book-footer-link">Mike P. Sinn</a> |
    <a href="https://creativecommons.org/licenses/by-nc/4.0/" class="book-footer-link">CC BY-NC 4.0</a> |
    <a href="https://manual.WarOnDisease.org/knowledge/about.html" class="book-footer-link">About &amp; Follow</a> |
    <a href="https://github.com/wishonia/earth-optimization-protocol" class="book-footer-link">&#128194; Source Code &amp; Data</a>
  </p>
{cta_html}
</div>
"""

    html_dir = project_root / "assets" / "html"
    html_dir.mkdir(parents=True, exist_ok=True)
    output_path = html_dir / "generated-footer.html"

    with open(output_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(html_content)

    # Clean up any per-site footer files from previous runs
    for old_file in html_dir.glob("generated-footer-*.html"):
        old_file.unlink()
        logger.debug("Removed old per-site footer: %s", old_file.name)

    logger.debug("Generated %s", output_path.relative_to(project_root))
    return output_path


def main():
    """CLI entry point."""
    if sys.platform == "win32":
        sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[union-attr]

    project_root = Path(__file__).parent.parent.absolute()

    logger.debug("Generating footer HTML...")
    output_path = generate_footer_html(project_root)
    logger.debug("Output: %s", output_path)


if __name__ == "__main__":
    main()
